spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    # ImMemory
    url: jdbc:h2:mem:hardwareshop
    #    tcp: jdbc:h2:tcp://localhost:9092/mem:hardwareshop
    # Relative path form current dir
    #    url: jdbc:h2:./db/hardwareshop
    # Relative path from home
    #    url: jdbc:h2:~/hardwareshop
    #    tcp: jdbc:h2:tcp://localhost:9092/~/hardwareshop
    username: sa
    password:
  h2.console.enabled: true

logging:
  level:
    root: WARN
    com.antontkach.hardwareshop: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG